---
name: Test Suite

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install the pipenv
        run: python -m pip install pipenv --user
      - name: Setup Python virtual environment
        run: |
          python -m pipenv install
          python -m pipenv install -d
          python -m pipenv run poetry install

      - name: Keycloak Admin Setup with Docker
        run: |
          docker run --name keycloak_server -d -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:25.0.2 start-dev
          sleep 180
          docker exec keycloak_server /bin/bash -c "cd /opt/keycloak/bin && ./kcadm.sh config credentials --server http://localhost:8080 --realm master --user admin --password admin"
          docker exec keycloak_server /bin/bash -c "cd /opt/keycloak/bin && ./kcadm.sh update realms/master -s sslRequired=NONE --server http://localhost:8080"

      - name: Run the one_time_configure_client_credentials
        run: python -m pipenv run python ./tests/fixtures/one_time_configure_client_credentials.py

      - name: Run tests
        run: python -m pipenv run pytest
